global:
  scrape_interval: 15s  # How frequently Prometheus scrapes targets by default

scrape_configs:
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
    - role: endpoints

  - job_name: 'book-catalog'
    static_configs:
      - targets: ['book-catalog:8000']

  - job_name: 'inventory-management'
    static_configs:
      - targets: ['inventory-management:8000']
