# Your Solution
version: '3'
services: 
     
  book-catalog:
    image: book-catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
    - "4000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://sit722_9_2_vish_user:PmD5POiEr3u0lHMZDSX5ty5G8rysrcIM@dpg-cs364056l47c73eaccig-a.singapore-postgres.render.com/sit722_9_2_vish
    restart: "no"

  inventory-management:
    image: inventory-management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
    - "4001:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://sit722_9_2_vish_user:PmD5POiEr3u0lHMZDSX5ty5G8rysrcIM@dpg-cs364056l47c73eaccig-a.singapore-postgres.render.com/sit722_9_2_vish