name: Deploy microservice

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      # Installs Kubectl and connects it to the cluster.
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      # Install Helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      # Add Prometheus Helm repo
      - name: Add Prometheus Helm repo
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      # Add Grafana Helm repo
      - name: Add the official Grafana Helm repo
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

      # Install Prometheus
      - name: Install Prometheus
        run: |
          helm upgrade --install prometheus prometheus-community/prometheus

      # Install or Upgrade Grafana
      - name: Install or Upgrade Grafana
        run: |
          helm upgrade --install grafana grafana/grafana --set adminPassword=admin

      # Set Up Port Forwarding (Optional)
      - name: Set Up Port Forwarding (Optional)
        run: |
          kubectl port-forward svc/grafana 3000:80 &
          kubectl port-forward svc/prometheus-server 9090:80 &

      # Build Docker image
      - name: Build Docker Image
        run: ./scripts/build-image.sh

      # Push Docker image
      - name: Push Docker Image
        run: ./scripts/push-image.sh

      # Deploy the microservice
      - name: Deploy Application
        run: ./scripts/deploy.sh
